from django.urls import path

from router import views as router_views
from router.api import views

urlpatterns = [
    path("apikey", views.register_apikey),
    path("request_stats", views.request_stats),
    path("total_request_count", views.total_request_count),
    path("input_token", views.input_token),
    path("output_token", views.output_token),
    path("token_summary", views.token_summary),
    path("model_request_stats", views.model_request_stats),
    path("all_model_request_stats", views.all_model_request_stats),
    path("models", views.models),
    path("model_online_list", views.model_online_list),
    path("model_info", views.model_info),
    path("request_time_stats", views.request_time_stats),
    path("model_request_time_stats", views.model_request_time_stats),
    path("model_request_count_by_period", views.model_request_count_by_period),
    path("model_ip_count_by_period", views.model_ip_count_by_period),
    path("model_latency_boxplot", views.model_latency_boxplot),
    path("download/ai_assistant", views.download_ai_assistant),
    path("whitelist/update", router_views.whitelist_update),
    path("refresh_user_info", router_views.refresh_user_info),
    path("add_server", views.add_server),
    path("mr_live_review", views.upsert_mr_live_review),
    path("mr_live_review/stats", views.mr_live_review_stats),
    path("mr_live_review/stats_by_confidence", views.mr_live_review_stats_by_confidence),
    path("mr_live_review/stats_by_date", views.mr_live_review_stats_by_date),
    path("mr_live_review/list", views.mr_live_review_list),
    path("mr_live_review/list_by_confidence", views.mr_live_review_list_by_confidence),
    path("daily_mr_review", views.create_daily_mr_review),
    path("live_review_requests", views.create_live_review_request),
    path("codehub_review", views.upsert_codehub_review),
    path("concurrent_multiplier/update", views.update_concurrent_multiplier),
    path("ai_assistant_user_feedback", views.create_ai_assistant_user_feedback),
    path("ai_assistant_user_feedback/list", views.ai_assistant_user_feedback_list),
    path("ai_assistant_user_feedback/update", views.update_ai_assistant_user_feedback),
    path("access_stats_by_department", views.access_stats_by_department),
    path("access_stats_by_department/export", views.export_access_stats_csv),
    path("department/cascade", views.department_cascade),
    path("whitelist/list", views.whitelist_list),
    path("ip/list", views.ip_list_with_user_info),
    path("codehub_review/stats", views.codehub_review_stats),
    path("codehub_review/category_stats", views.codehub_review_category_stats),
    path("codehub_review/severity_stats", views.codehub_review_severity_stats),
    path("codehub_review/list", views.codehub_review_list),
    path("codehub_review/update", views.update_codehub_review),
    path("codehub_review/relative_path_list", views.codehub_review_relative_path_list),
    path("codehub_review/severity_list", views.codehub_review_severity_list),
    path("codehub_review/issue_category_list", views.codehub_review_issue_category_list),
    path("review_slice", views.create_review_slice),
    path("review_summary", views.create_review_summary),
]
